version: 0.1
storage:
  root: 
  experiments: exps/ # Experiments root contains a list of definition files for each
  datasets_subdir: datasets/ # root for train
  models_subdir: models/ # root for trained models
  expand_out: expand_out/ # Expansion output
logging: NOTSET

lexicons:
  liwc2015:
    dic: 
  values:
    csv: 
  liwc22:
    tool_out: 
    csv: 

lists:
  names:
    lst: 
  stopwords:
    lst:

dictionaries:
  urban_dictionary:
    csv: 
    raw: 
  wiktionary:
    csv: 